In [1]:
import pandas as pd

def clean(file_path, out_file):
    '''
    Data cleaning pipeline:
    Renaming columns and rearranging column orders
    Converting 'date' column into a datetime object
    Adding 'day_of_the_week' classifier
    Removing unneccessary columns
    '''
    names = ['c_a', 'unit', 'scp', 'station', 'linename', 'division', 
             'date', 'time', 'desc', 'entries', 'exits']
    df = pd.read_csv(file_path, names=names, skiprows=1)
    df['date'] = pd.to_datetime(df['date'])
    df['day_of_week'] = df['date'].dt.day_name()
    df = df[['station', 'unit', 'c_a', 'scp', 'date', 'day_of_week', 'time', 'entries', 'exits']]
    #return df
    return df.to_pickle(out_file)

In [2]:
clean('http://web.mta.info/developers/data/nyct/turnstile/turnstile_200627.txt', '200627')

In [3]:
df = pd.read_pickle('200627')
df[:43]

,station,unit,c_a,scp,date,day_of_week,time,entries,exits
0,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,00:00:00,7424218,2522558
1,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,04:00:00,7424220,2522559
2,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,08:00:00,7424231,2522572
3,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,12:00:00,7424265,2522590
4,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,16:00:00,7424340,2522604
5,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,20:00:00,7424415,2522612
6,59 ST,R051,A002,02-00-00,2020-06-21,Sunday,00:00:00,7424441,2522622
7,59 ST,R051,A002,02-00-00,2020-06-21,Sunday,04:00:00,7424443,2522623
8,59 ST,R051,A002,02-00-00,2020-06-21,Sunday,08:00:00,7424457,2522628
9,59 ST,R051,A002,02-00-00,2020-06-21,Sunday,12:00:00,7424471,2522645
10,59 ST,R051,A002,02-00-00,2020-06-21,Sunday,16:00:00,7424503,2522656
11,59 ST,R051,A002,02-00-00,2020-06-21,Sunday,20:00:00,7424558,2522667
12,59 ST,R051,A002,02-00-00,2020-06-22,Monday,00:00:00,7424584,2522674
13,59 ST,R051,A002,02-00-00,2020-06-22,Monday,04:00:00,7424588,2522674
14,59 ST,R051,A002,02-00-00,2020-06-22,Monday,08:00:00,7424604,2522708
15,59 ST,R051,A002,02-00-00,2020-06-22,Monday,12:00:00,7424640,2522767
16,59 ST,R051,A002,02-00-00,2020-06-22,Monday,16:00:00,7424743,2522794
17,59 ST,R051,A002,02-00-00,2020-06-22,Monday,20:00:00,7424927,2522815
18,59 ST,R051,A002,02-00-00,2020-06-23,Tuesday,00:00:00,7424961,2522827
19,59 ST,R051,A002,02-00-00,2020-06-23,Tuesday,04:00:00,7424962,2522830
20,59 ST,R051,A002,02-00-00,2020-06-23,Tuesday,08:00:00,7424962,2522865
21,59 ST,R051,A002,02-00-00,2020-06-23,Tuesday,12:00:00,7424987,2522921
22,59 ST,R051,A002,02-00-00,2020-06-23,Tuesday,16:00:00,7425091,2522934
23,59 ST,R051,A002,02-00-00,2020-06-23,Tuesday,20:00:00,7425282,2522958
24,59 ST,R051,A002,02-00-00,2020-06-24,Wednesday,00:00:00,7425307,2522966
25,59 ST,R051,A002,02-00-00,2020-06-24,Wednesday,04:00:00,7425308,2522966
26,59 ST,R051,A002,02-00-00,2020-06-24,Wednesday,08:00:00,7425323,2522985
27,59 ST,R051,A002,02-00-00,2020-06-24,Wednesday,12:00:00,7425356,2523073
28,59 ST,R051,A002,02-00-00,2020-06-24,Wednesday,16:00:00,7425446,2523097
29,59 ST,R051,A002,02-00-00,2020-06-24,Wednesday,20:00:00,7425641,2523117
30,59 ST,R051,A002,02-00-00,2020-06-25,Thursday,00:00:00,7425675,2523122
31,59 ST,R051,A002,02-00-00,2020-06-25,Thursday,04:00:00,7425677,2523122
32,59 ST,R051,A002,02-00-00,2020-06-25,Thursday,08:00:00,7425682,2523167
33,59 ST,R051,A002,02-00-00,2020-06-25,Thursday,12:00:00,7425714,2523227
34,59 ST,R051,A002,02-00-00,2020-06-25,Thursday,16:00:00,7425817,2523251
35,59 ST,R051,A002,02-00-00,2020-06-25,Thursday,20:00:00,7425995,2523266
36,59 ST,R051,A002,02-00-00,2020-06-26,Friday,00:00:00,7426030,2523275
37,59 ST,R051,A002,02-00-00,2020-06-26,Friday,04:00:00,7426033,2523277
38,59 ST,R051,A002,02-00-00,2020-06-26,Friday,08:00:00,7426050,2523323
39,59 ST,R051,A002,02-00-00,2020-06-26,Friday,12:00:00,7426087,2523383
40,59 ST,R051,A002,02-00-00,2020-06-26,Friday,16:00:00,7426221,2523419
41,59 ST,R051,A002,02-00-00,2020-06-26,Friday,20:00:00,7426405,2523435
42,59 ST,R051,A002,02-00-01,2020-06-20,Saturday,00:00:00,6597712,1486866

In [4]:
i = 0
j = 42
dfs = []
while j <= len(df)+42:
    scp_deltas = df[i:j][['entries', 'exits']].diff()
    dfs.append(scp_deltas)
    i+=42
    j+=42

In [5]:
deltas = pd.concat(dfs)
deltas

        entries  exits
0           NaN    NaN
1           2.0    1.0
2          11.0   13.0
3          34.0   18.0
4          75.0   14.0
...         ...    ...
206666      0.0    0.0
206667      0.0    0.0
206668      0.0    0.0
206669      0.0    0.0
206670      0.0    0.0

[206671 rows x 2 columns]

In [6]:
deltas.shape, df.shape

((206671, 2), (206671, 9))

In [7]:
df['delta_entries'] = deltas.entries
df['delta_exits'] = deltas.exits
df

,station,unit,c_a,scp,date,day_of_week,time,entries,exits,delta_entries,delta_exits
0,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,00:00:00,7424218,2522558,NaN,NaN
1,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,04:00:00,7424220,2522559,2.0,1.0
2,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,08:00:00,7424231,2522572,11.0,13.0
3,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,12:00:00,7424265,2522590,34.0,18.0
4,59 ST,R051,A002,02-00-00,2020-06-20,Saturday,16:00:00,7424340,2522604,75.0,14.0
...,...,...,...,...,...,...,...,...,...,...,...
206666,RIT-ROOSEVELT,R469,TRAM2,00-05-01,2020-06-26,Friday,05:00:00,5554,514,0.0,0.0
206667,RIT-ROOSEVELT,R469,TRAM2,00-05-01,2020-06-26,Friday,09:00:00,5554,514,0.0,0.0
206668,RIT-ROOSEVELT,R469,TRAM2,00-05-01,2020-06-26,Friday,13:00:00,5554,514,0.0,0.0
206669,RIT-ROOSEVELT,R469,TRAM2,00-05-01,2020-06-26,Friday,17:00:00,5554,514,0.0,0.0
206670,RIT-ROOSEVELT,R469,TRAM2,00-05-01,2020-06-26,Friday,21:00:00,5554,514,0.0,0.0

In [8]:
pd.to_pickle(df, 'Delta Dataframe')