In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('http://web.mta.info/developers/data/nyct/turnstile/turnstile_200627.txt')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 206671 entries, 0 to 206670
Data columns (total 11 columns):
 #   Column                                                                Non-Null Count   Dtype
---  ------                                                                --------------   -----
 0   C/A                                                                   206671 non-null  object
 1   UNIT                                                                  206671 non-null  object
 2   SCP                                                                   206671 non-null  object
 3   STATION                                                               206671 non-null  object
 4   LINENAME                                                              206671 non-null  object
 5   DIVISION                                                              206671 non-null  object
 6   DATE                                                                  206671 non-null  object
 7   TIME                                                                  206671 non-null  object
 8   DESC                                                                  206671 non-null  object
 9   ENTRIES                                                               206671 non-null  int64
 10  EXITS                                                                 206671 non-null  int64
dtypes: int64(2), object(9)
memory usage: 17.3+ MB

In [4]:
df.head(50)

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2020,00:00:00,REGULAR,7424218,2522558
1,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2020,04:00:00,REGULAR,7424220,2522559
2,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2020,08:00:00,REGULAR,7424231,2522572
3,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2020,12:00:00,REGULAR,7424265,2522590
4,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2020,16:00:00,REGULAR,7424340,2522604
5,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/20/2020,20:00:00,REGULAR,7424415,2522612
6,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/21/2020,00:00:00,REGULAR,7424441,2522622
7,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/21/2020,04:00:00,REGULAR,7424443,2522623
8,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/21/2020,08:00:00,REGULAR,7424457,2522628
9,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/21/2020,12:00:00,REGULAR,7424471,2522645
10,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/21/2020,16:00:00,REGULAR,7424503,2522656
11,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/21/2020,20:00:00,REGULAR,7424558,2522667
12,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/22/2020,00:00:00,REGULAR,7424584,2522674
13,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/22/2020,04:00:00,REGULAR,7424588,2522674
14,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/22/2020,08:00:00,REGULAR,7424604,2522708
15,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/22/2020,12:00:00,REGULAR,7424640,2522767
16,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/22/2020,16:00:00,REGULAR,7424743,2522794
17,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/22/2020,20:00:00,REGULAR,7424927,2522815
18,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/23/2020,00:00:00,REGULAR,7424961,2522827
19,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/23/2020,04:00:00,REGULAR,7424962,2522830
20,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/23/2020,08:00:00,REGULAR,7424962,2522865
21,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/23/2020,12:00:00,REGULAR,7424987,2522921
22,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/23/2020,16:00:00,REGULAR,7425091,2522934
23,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/23/2020,20:00:00,REGULAR,7425282,2522958
24,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/24/2020,00:00:00,REGULAR,7425307,2522966
25,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/24/2020,04:00:00,REGULAR,7425308,2522966
26,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/24/2020,08:00:00,REGULAR,7425323,2522985
27,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/24/2020,12:00:00,REGULAR,7425356,2523073
28,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/24/2020,16:00:00,REGULAR,7425446,2523097
29,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/24/2020,20:00:00,REGULAR,7425641,2523117
30,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/25/2020,00:00:00,REGULAR,7425675,2523122
31,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/25/2020,04:00:00,REGULAR,7425677,2523122
32,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/25/2020,08:00:00,REGULAR,7425682,2523167
33,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/25/2020,12:00:00,REGULAR,7425714,2523227
34,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/25/2020,16:00:00,REGULAR,7425817,2523251
35,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/25/2020,20:00:00,REGULAR,7425995,2523266
36,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/26/2020,00:00:00,REGULAR,7426030,2523275
37,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/26/2020,04:00:00,REGULAR,7426033,2523277
38,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/26/2020,08:00:00,REGULAR,7426050,2523323
39,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/26/2020,12:00:00,REGULAR,7426087,2523383
40,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/26/2020,16:00:00,REGULAR,7426221,2523419
41,A002,R051,02-00-00,59 ST,NQR456W,BMT,06/26/2020,20:00:00,REGULAR,7426405,2523435
42,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/20/2020,00:00:00,REGULAR,6597712,1486866
43,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/20/2020,04:00:00,REGULAR,6597714,1486866
44,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/20/2020,08:00:00,REGULAR,6597721,1486873
45,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/20/2020,12:00:00,REGULAR,6597742,1486899
46,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/20/2020,16:00:00,REGULAR,6597782,1486918
47,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/20/2020,20:00:00,REGULAR,6597821,1486921
48,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/21/2020,00:00:00,REGULAR,6597843,1486925
49,A002,R051,02-00-01,59 ST,NQR456W,BMT,06/21/2020,04:00:00,REGULAR,6597844,1486925

In [5]:
.rename(columns = {'C/A':'c_a', 'UNIT': 'unit', 'SCP': 'scp', 
                   'STATION':'station'})
df_grouped.head(30)

SyntaxError: invalid syntax (<ipython-input-5-bec4e342f2ae>, line 1)

In [6]:
df.columns

Index(['C/A', 'UNIT', 'SCP', 'STATION', 'LINENAME', 'DIVISION', 'DATE', 'TIME',
       'DESC', 'ENTRIES',
       'EXITS                                                               '],
      dtype='object')

In [7]:
df.TIME

0         00:00:00
1         04:00:00
2         08:00:00
3         12:00:00
4         16:00:00
            ...
206666    05:00:00
206667    09:00:00
206668    13:00:00
206669    17:00:00
206670    21:00:00
Name: TIME, Length: 206671, dtype: object

In [9]:
df.TIME

0         00:00:00
1         04:00:00
2         08:00:00
3         12:00:00
4         16:00:00
            ...
206666    05:00:00
206667    09:00:00
206668    13:00:00
206669    17:00:00
206670    21:00:00
Name: TIME, Length: 206671, dtype: object

In [19]:
date = df.DATE

In [22]:
def my_func(x):
    return x.split('/')
srd_unique = df['DATE'].apply(my_func).unique()

TypeError: unhashable type: 'list'

In [26]:
df.DATE.str.strip('/')

0         06/20/2020
1         06/20/2020
2         06/20/2020
3         06/20/2020
4         06/20/2020
             ...
206666    06/26/2020
206667    06/26/2020
206668    06/26/2020
206669    06/26/2020
206670    06/26/2020
Name: DATE, Length: 206671, dtype: object

In [34]:
df['date_working'] = df['DATE'].str.replace(r'/', '')

In [35]:
df['data_working']

0         06202020
1         06202020
2         06202020
3         06202020
4         06202020
            ...
206666    06262020
206667    06262020
206668    06262020
206669    06262020
206670    06262020
Name: DATE, Length: 206671, dtype: object

In [37]:
df['time_working']=df['TIME'].str.replace(r':','')

In [38]:
df['time_working']

0         000000
1         040000
2         080000
3         120000
4         160000
           ...
206666    050000
206667    090000
206668    130000
206669    170000
206670    210000
Name: time_working, Length: 206671, dtype: object

In [41]:
df['time_index'] = df['date_working'] + df['time_working']
df['time_index']

0         06202020000000
1         06202020040000
2         06202020080000
3         06202020120000
4         06202020160000
               ...
206666    06262020050000
206667    06262020090000
206668    06262020130000
206669    06262020170000
206670    06262020210000
Name: time_index, Length: 206671, dtype: object